### ISSUE TITLE
mismatch between installed package and package called in init to set the version

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/cookiecutter-mdakit#114]
The cookiecutter sets the package name using `cookiecutter.repo_name` here: https://github.com/MDAnalysis/cookiecutter-mdakit/blob/main/%7B%7Bcookiecutter.repo_name%7D%7D/pyproject.toml#L9

but then sets the version using `cookiecutter.package_name` here: https://github.com/MDAnalysis/cookiecutter-mdakit/blob/main/%7B%7Bcookiecutter.repo_name%7D%7D/pyproject.toml#L9

In some cases `cookiecutter.repo_name` != `cookiecutter.package_name` (for example when @orbeckst created mdgeomkit, repo_name=mdgeomkit, and package_name=mdgeom). When this occurs the init version setter fails because it can't find the installed package.

**Comment by lilyminium** [comment]
I believe this was fixed in #116.
