### ISSUE TITLE
change repo name to cookiecutter-MDAKit

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/cookiecutter-mdakit#13]
Given than we want to use the cookiecutter for MDAKits, I suggest to make this explicit in the name and call it **cookiecutter-mdakit** or appropriately capitalized.

**Comment by lilyminium** [comment]
I'm on board with this -- will do so in a day or two unless there are any objections.

**Comment by lilyminium** [comment]
Changed to cookiecutter-mdakit -- please reopen if the capitalisation should be less lowercase.
