### ISSUE TITLE
Docs URL

### ISSUE THREAD

**Issue by lilyminium** [MDAnalysis/cookiecutter-mdakit#18]
Docs (which need updating) currently point to https://cookiecutter-mdakit.readthedocs.io/en/latest/?badge=latest . Do we want to move it to a subdomain, like docs.mdanalysis.org and userguide.mdanalysis.org?

Options include:

* cookiecutter.mdanalysis.org
* cookiecutter-mdakit.mdanalysis.org
* mdakits.mdanalysis.org (ideally this URL would be a more general location for all mdakit stuff, though)
* mdakits.mdanalysis.org/cookiecutter <-- I think this can work as a submodule of an overall mdakits repository
* do nothing, stay on RTD

It would be good to have this cleared up as we start working on cookiecutter docs, so we start off pointing people in the right direction.

Comments from @MDAnalysis/coredevs welcomed.

**Comment by orbeckst** [comment]
Ultimately, having mdakits.mdanalysis.org for all MDAKit stuff would be nice.

Right now, we can also just do the usual www.mdanalysis.org/cookiecutter-mdakit.

**Comment by IAlibay** [comment]
I actually like the idea of the cookiecutter being a it's own product, i.e. you don't have to expect to be an mdakit to want to use the cookiecutter (i.e. you might just like this cookiecutter better than the alternatives).

I would vote for cookiecutter.mdanalysis.org or www.mdanalysis.org/cookiecutter or www.mdanalysis.org/cookiecutter-mdakit
