### ISSUE TITLE
Agree to releasing MDAnalysisTests' dummy.py under an MIT license

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/cookiecutter-mdakit#20]
Follow up from #19 - we'd like to have `make_Universe` be available under the cookiecutter without having folks need to have a whole copy of MDAnalysisTests (which is > 40 MB as a tarball).

As such we were wondering if we could get the code authors for that file to agree to have the code be released under MIT conditions.

The authors of that file are (in order of most contributions):
  - [x] @mnmelo
  - [x] @orbeckst 
  - [x] @IAlibay 
  - [x] @richardjgowers

**Comment by IAlibay** [comment]
I'm happy for the contents of that file as they currently exist (as of the 26th of July 2022) to be under an MIT license.

**Comment by orbeckst** [comment]
I am happy to license the contents of this file to be licensed under MIT henceforth.

**Comment by richardjgowers** [comment]
I'm happy for the contents of that file as they currently exist (as of the 26th of July 2022) to be under an MIT license.

**Comment by IAlibay** [comment]
@mnmelo could I ping you again about this please?

**Comment by mnmelo** [comment]
Sorry, this had fallen through my attention. I'm ok with it.

**Comment by mnmelo** [comment]
Or, more formally,
I'm happy for the contents of that file as they currently exist (as of the 6th of January 2024) to be under an MIT license.

**Comment by IAlibay** [comment]
thanks @mnmelo ! (and everyone else)

**Comment by IAlibay** [comment]
As far as I'm aware there are no code changes to be made here - just the cookiecutter can remain MIT.
