### ISSUE TITLE
Update cookiecutter to use Mambaforge instead of "mamba-version".

### ISSUE THREAD

**Issue by IAlibay** [MDAnalysis/cookiecutter-mdakit#37]
Alternatively we could look unto using micromamba if someone has strong views on this.

**Comment by IAlibay** [comment]
tagging @ianmkenney

**Comment by lilyminium** [comment]
Fixed in #38

**Comment by IAlibay** [comment]
I'm going to re-open this, I don't think #38 actually fixed the problem unfortunately, it changes the CI file for the repo but it doesn't change: https://github.com/MDAnalysis/cookiecutter-mdakit/blob/6d393656eafbae2e28d9672e57ab5ed0c40f184c/%7B%7Bcookiecutter.repo_name%7D%7D/.github/workflows/%7B%7Bcookiecutter._ci_name%7D%7D.yaml#L76 ?
