### ISSUE TITLE
Default pip flags in generated README should not include "editable"

### ISSUE THREAD

**Issue by ianmkenney** [MDAnalysis/cookiecutter-mdakit#78]
In the generated README, we instruct the user to install with the `-e` flag. This isn't really the best option by default.

https://github.com/MDAnalysis/cookiecutter-mdakit/blob/457bcde335795e2bf9e467ec0681dfe3f91fc431/%7B%7Bcookiecutter.repo_name%7D%7D/README.md?plain=1#L41-L45

**Comment by lilyminium** [comment]
Ahh good point. Could you open a PR please?
