### ISSUE TITLE
Generated test module will be included by default in sphinx docs

### ISSUE THREAD

**Issue by ianmkenney** [MDAnalysis/cookiecutter-mdakit#81]
I'm sure that, most of the time, developers don't care much about having user facing documentation for tests. With the recursive autodocs, these modules are included by default. We should be able to remove them with something like

```python
autodoc_mock_imports = [
    '{{mykit}}.tests',
]
```

to `conf.py`.

**Comment by lilyminium** [comment]
Thanks for raising this @ianmkenney! sounds like a good solution -- could you please open a PR?
