### ISSUE TITLE
Python 3.12 compatibility with versioneer

### ISSUE THREAD

**Issue by ianmkenney** [MDAnalysis/cookiecutter-mdakit#91]
As it stands, versioneer v0.29, the latest release, does not support Python 3.12. Note we are shipping v0.18. Supposedly this is fixed in the main versioneer repo (https://github.com/python-versioneer/python-versioneer/pull/376).

I see this being an real headache for new users since `setup.py` uses `versioneer.get_version()`. It seems that all MDAKits built with the cookiecutter will fail with for Python 3.12.

**Comment by IAlibay** [comment]
latest versioneer will work here - that or we finally do this: #53

**Comment by lilyminium** [comment]
Ah... yes let's switch to #53, it looks slightly more futureproof than even build-time versioneer.
